# Generated by Django 3.0.8 on 2020-08-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200802_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='workouts',
            field=models.ManyToManyField(related_name='category', to='workouts.Workout'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('day', models.CharField(max_length=6)),
                ('categories', models.ManyToManyField(related_name='schedule_categories', to='workouts.Category')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='workouts.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='CreatedSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedule', to='workouts.Schedule')),
            ],
        ),
    ]
