# Generated by Django 3.0.8 on 2020-08-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20200807_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='schedule_categories', to='workouts.Category'),
        ),
    ]
