# Generated by Django 3.0.8 on 2020-08-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20200807_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetail',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_workouts', to='workouts.Workout'),
        ),
    ]
