# Generated by Django 3.0.8 on 2020-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='time',
        ),
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
