# Generated by Django 3.0.8 on 2020-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200802_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
