# Generated by Django 3.0.8 on 2020-08-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20200807_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('day', models.CharField(max_length=6)),
                ('categories', models.ManyToManyField(related_name='schedule_categories', to='workouts.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='workout',
        ),
        migrations.AddField(
            model_name='schedule',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CreatedSchedules',
        ),
        migrations.AddField(
            model_name='scheduledetail',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_detail', to='workouts.Schedule'),
        ),
        migrations.AddField(
            model_name='scheduledetail',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_workouts', to='workouts.Workout'),
        ),
    ]
