# Generated by Django 3.0.8 on 2020-08-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20200807_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledetail',
            name='categories',
        ),
    ]
